### ISSUE TITLE
Need better instructions for installing dependencies

### ISSUE THREAD

**Issue by dataplayer12** [lightonai/dfa-scales-to-modern-deep-learning#1]
Congratulations on your paper. I was trying to play around a bit and found that the dependencies are not easy to install (at least on arm64)

1. The requirements file is missing an `=` sign on line that refers to seaborn.
2. The package `sentencepiece==1.9.0` is not available with pip on arm64.
3. `torch==1.5.0+cu101` is not available with pip

The first two problems are easily fixable and the third one too, but having encountered three hiccups in installing just half of the dependencies listed in `requirements.txt`, I decided to file this issue. Please add better instructions for installing dependencies, or if possible, please provide docker images (arm64 compatible) to solve all hassles in one go.

**Comment by slippylolo** [comment]
Hey, 
Thank you for your interest in our work! 

1. Fixed in commit [66efb4b](https://github.com/lightonai/dfa-scales-to-modern-deep-learning/commit/66efb4b4ef8a378bf01ea0e5e6794d6bb4380c97). 
2. Sadly, I don't have access to an `arm64` platform. I can't provide an immediate resolution. 
3. `pip install torch==1.5.1+cu101 torchvision==0.6.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html` should work. 

Providing a more streamlined installation process is in our todo list for the future, but I don't have the bandwidth to immediately take care of this. You are welcome to submit a pull request if you end up fixing these issues on your side. 

Also, note that most of the dependencies (like `sentencepiece`) are task-specific. Given the large range of applications considered, it may be easier for you to tailor the installation to your needs. In particular, our [DFA implementation](https://github.com/lightonai/dfa-scales-to-modern-deep-learning/tree/master/TinyDFA) has minimal dependencies: only `torch` (and `torchvision` for the MNIST example) are required.

**Comment by dataplayer12** [comment]
Hi, thank you for making the fix. The issue is partly that I am using a strange platform (NVIDIA Jetson), which should be supported in principle but the software ecosystem for Jetson is different from x86 (for example, `pip install torch==xx` is not possible). I may contribute to a patch in the future to add support for arm64, but for the moment I have switched to x86.
